name: Publish bun-fs-js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/bun-fs-js/**'

concurrency:
  group: packages-publish
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netapplabs'
      - name: Set up Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netapplabs'
      - name: yarn-install
        run: |
          corepack enable
          corepack prepare yarn --activate
          yarn install --frozen-lock-file
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install
        working-directory: packages/bun-fs-js
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Bun Tests
        run: bun test
        working-directory: packages/bun-fs-js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version
        run: bunx standard-version -t packages/bun-fs-js@
        working-directory: packages/bun-fs-js

      - name: Build package
        run: bun run build
        working-directory: packages/bun-fs-js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: bun run push
        working-directory: packages/bun-fs-js
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push version bump
        run: |
          git push
